import { useAppEffects } from "@/app/hooks/use-app-effects";
import { useAppState } from "@/app/hooks/use-app-state";
import { buildAppViewModels } from "@/app/hooks/use-app-view-models";
import { useProviderAndSettingsActions } from "@/app/hooks/use-provider-and-settings-actions";
import { useReviewActions } from "@/app/hooks/use-review-actions";

export function useAppController() {
  const s = useAppState();

  const {
    openSettings,
    closeSettings,
    openDeviceVerificationUrl,
    handleStartDeviceAuth,
    handleConnectProvider,
    handleDisconnectProvider,
    handleCloneRepository,
    handlePickDestinationRoot,
    handlePickLocalProject,
    handleCreateLocalProjectThread,
    handleAddLocalRepoFromSidebar,
    isRepoCollapsed,
    repoDisplayName,
    isRepoMenuOpen,
    toggleRepoCollapsed,
    setRepoMenuOpenState,
    handleCreateReviewForRepo,
    handleRenameRepo,
    handleRemoveRepo,
    handleRemoveReview,
    handleOpenDiffsDocs,
    handleSaveAiSettings,
    handleSwitchAppServerAccount,
    handleRefreshAppServerAccountStatus,
    handleSaveAiApiKey,
  } = useProviderAndSettingsActions({
    providerState: {
      selectedProvider: s.selectedProvider,
      setSelectedProvider: s.setSelectedProvider,
      providerToken: s.providerToken,
      setProviderToken: s.setProviderToken,
      repositoryInput: s.repositoryInput,
      setRepositoryInput: s.setRepositoryInput,
      destinationRoot: s.destinationRoot,
      setDestinationRoot: s.setDestinationRoot,
      localProjectPath: s.localProjectPath,
      setLocalProjectPath: s.setLocalProjectPath,
      providerBusy: s.providerBusy,
      setProviderBusy: s.setProviderBusy,
      providerError: s.providerError,
      setProviderError: s.setProviderError,
      providerStatus: s.providerStatus,
      setProviderStatus: s.setProviderStatus,
      deviceAuthInProgress: s.deviceAuthInProgress,
      setDeviceAuthInProgress: s.setDeviceAuthInProgress,
      deviceAuthUserCode: s.deviceAuthUserCode,
      setDeviceAuthUserCode: s.setDeviceAuthUserCode,
      deviceAuthVerificationUrl: s.deviceAuthVerificationUrl,
      setDeviceAuthVerificationUrl: s.setDeviceAuthVerificationUrl,
    },
    navigation: {
      setActiveView: s.setActiveView,
      setActiveSettingsTab: s.setActiveSettingsTab,
    },
    connectionRefetch: {
      refetchGithubConnection: s.refetchGithubConnection,
      refetchGitlabConnection: s.refetchGitlabConnection,
    },
    repoState: {
      refetchThreads: s.refetchThreads,
      setSelectedThreadId: s.setSelectedThreadId,
      selectedBaseRef: s.selectedBaseRef,
      setSelectedBaseRef: s.setSelectedBaseRef,
      reviewDefaultsByRepo: s.reviewDefaultsByRepo,
      setReviewDefaultsByRepo: s.setReviewDefaultsByRepo,
      knownRepoWorkspaces: s.knownRepoWorkspaces,
      setKnownRepoWorkspaces: s.setKnownRepoWorkspaces,
      repoDisplayNames: s.repoDisplayNames,
      setRepoDisplayNames: s.setRepoDisplayNames,
      collapsedRepos: s.collapsedRepos,
      setCollapsedRepos: s.setCollapsedRepos,
      repoMenuOpen: s.repoMenuOpen,
      setRepoMenuOpen: s.setRepoMenuOpen,
    },
    settingsState: {
      setSettingsError: s.setSettingsError,
    },
    aiSettingsState: {
      aiReviewProviderInput: s.aiReviewProviderInput,
      aiReviewModelInput: s.aiReviewModelInput,
      aiOpencodeProviderInput: s.aiOpencodeProviderInput,
      aiOpencodeModelInput: s.aiOpencodeModelInput,
      aiSettingsBusy: s.aiSettingsBusy,
      setAiSettingsBusy: s.setAiSettingsBusy,
      setAiSettingsError: s.setAiSettingsError,
      setAiSettingsStatus: s.setAiSettingsStatus,
      refetchAiReviewConfig: s.refetchAiReviewConfig,
    },
    accountState: {
      appServerAuthBusy: s.appServerAuthBusy,
      setAppServerAuthBusy: s.setAppServerAuthBusy,
      setAppServerAuthError: s.setAppServerAuthError,
      setAppServerAuthStatus: s.setAppServerAuthStatus,
      refetchAppServerAccountStatus: s.refetchAppServerAccountStatus,
      refetchOpencodeSidecarStatus: s.refetchOpencodeSidecarStatus,
    },
    apiKeyState: {
      aiApiKeyInput: s.aiApiKeyInput,
      setAiApiKeyInput: s.setAiApiKeyInput,
      aiApiKeyBusy: s.aiApiKeyBusy,
      setAiApiKeyBusy: s.setAiApiKeyBusy,
      setAiApiKeyError: s.setAiApiKeyError,
      setAiApiKeyStatus: s.setAiApiKeyStatus,
    },
  });

  const {
    handleCheckoutBranch,
    handleStartCreateBranch,
    handleCreateAndCheckoutBranch,
    handleCompareSelectedReview,
    handleStartAiReviewOnFullDiff,
    handleCancelAiReviewRun,
    handleAskAiFollowUp,
  } = useReviewActions({
    selection: {
      selectedThreadId: s.selectedThreadId,
      selectedWorkspace: s.selectedWorkspace,
      selectedBaseRef: s.selectedBaseRef,
      setSelectedBaseRef: s.setSelectedBaseRef,
    },
    compare: {
      compareResult: s.compareResult,
      setCompareResult: s.setCompareResult,
      setCompareBusy: s.setCompareBusy,
      setCompareError: s.setCompareError,
      setShowDiffViewer: s.setShowDiffViewer,
    },
    branch: {
      setBranchPopoverOpen: s.setBranchPopoverOpen,
      setBranchCreateMode: s.setBranchCreateMode,
      branchSearchQuery: s.branchSearchQuery,
      newBranchName: s.newBranchName,
      setNewBranchName: s.setNewBranchName,
      setBranchActionBusy: s.setBranchActionBusy,
      setBranchActionError: s.setBranchActionError,
      refetchWorkspaceBranches: s.refetchWorkspaceBranches,
    },
    ai: {
      prompt: s.aiPrompt,
      setPrompt: s.setAiPrompt,
      setAiReviewBusy: s.setAiReviewBusy,
      setAiFollowUpBusy: s.setAiFollowUpBusy,
      setAiReviewError: s.setAiReviewError,
      setAiStatus: s.setAiStatus,
      setAiChunkReviews: s.setAiChunkReviews,
      setAiFindings: s.setAiFindings,
      setAiProgressEvents: s.setAiProgressEvents,
      refetchThreadMessages: s.refetchThreadMessages,
      refetchAiReviewRuns: s.refetchAiReviewRuns,
    },
    review: {
      activeReviewScope: s.activeReviewScope,
      setActiveReviewScope: s.setActiveReviewScope,
      setReviewRuns: s.setReviewRuns,
      setSelectedRunId: s.setSelectedRunId,
      setReviewWorkbenchTab: s.setReviewWorkbenchTab,
    },
  });

  useAppEffects({
    selectedDiffTheme: s.selectedDiffTheme,
    knownRepoWorkspaces: s.knownRepoWorkspaces,
    setKnownRepoWorkspaces: s.setKnownRepoWorkspaces,
    repoDisplayNames: s.repoDisplayNames,
    repoGroups: s.repoGroups,
    selectedThreadId: s.selectedThreadId,
    setSelectedThreadId: s.setSelectedThreadId,
    setCompareError: s.setCompareError,
    setCompareResult: s.setCompareResult,
    setShowDiffViewer: s.setShowDiffViewer,
    setBranchPopoverOpen: s.setBranchPopoverOpen,
    setBranchSearchQuery: s.setBranchSearchQuery,
    setBranchCreateMode: s.setBranchCreateMode,
    setNewBranchName: s.setNewBranchName,
    setBranchActionError: s.setBranchActionError,
    setAiPrompt: s.setAiPrompt,
    setAiFollowUpBusy: s.setAiFollowUpBusy,
    setAiReviewError: s.setAiReviewError,
    setAiStatus: s.setAiStatus,
    setAiChunkReviews: s.setAiChunkReviews,
    setAiFindings: s.setAiFindings,
    setAiProgressEvents: s.setAiProgressEvents,
    branchPopoverOpen: s.branchPopoverOpen,
    selectedWorkspace: s.selectedWorkspace,
    refetchWorkspaceBranches: s.refetchWorkspaceBranches,
    getBranchSearchInputRef: s.getBranchSearchInputRef,
    branchCreateMode: s.branchCreateMode,
    getBranchCreateInputRef: s.getBranchCreateInputRef,
    aiReviewConfig: s.aiReviewConfig,
    setAiReviewProviderInput: s.setAiReviewProviderInput,
    setAiReviewModelInput: s.setAiReviewModelInput,
    setAiOpencodeProviderInput: s.setAiOpencodeProviderInput,
    setAiOpencodeModelInput: s.setAiOpencodeModelInput,
    setAiReviewBusy: s.setAiReviewBusy,
    persistedReviewRuns: s.persistedReviewRuns,
    refetchThreadMessages: s.refetchThreadMessages,
    refetchAiReviewRuns: s.refetchAiReviewRuns,
    aiReviewBusy: s.aiReviewBusy,
    setAiRunElapsedSeconds: s.setAiRunElapsedSeconds,
    setActiveReviewScope: s.setActiveReviewScope,
    setReviewRuns: s.setReviewRuns,
    selectedRunId: s.selectedRunId,
    setSelectedRunId: s.setSelectedRunId,
    setReviewWorkbenchTab: s.setReviewWorkbenchTab,
    maskAccountEmail: s.maskAccountEmail,
    reviewSidebarCollapsed: s.reviewSidebarCollapsed,
    setReviewSidebarCollapsed: s.setReviewSidebarCollapsed,
    reviewDefaultsByRepo: s.reviewDefaultsByRepo,
    handleCompareSelectedReview,
  });

  const { settingsViewModel, workspaceViewModel } = buildAppViewModels({
    state: s,
    providerActions: {
      openSettings,
      closeSettings,
      openDeviceVerificationUrl,
      handleStartDeviceAuth,
      handleConnectProvider,
      handleDisconnectProvider,
      handleCloneRepository,
      handlePickDestinationRoot,
      handlePickLocalProject,
      handleCreateLocalProjectThread,
      handleAddLocalRepoFromSidebar,
      isRepoCollapsed,
      repoDisplayName,
      isRepoMenuOpen,
      toggleRepoCollapsed,
      setRepoMenuOpenState,
      handleCreateReviewForRepo,
      handleRenameRepo,
      handleRemoveRepo,
      handleRemoveReview,
      handleOpenDiffsDocs,
      handleSaveAiSettings,
      handleSwitchAppServerAccount,
      handleRefreshAppServerAccountStatus,
      handleSaveAiApiKey,
    },
    reviewActions: {
      handleCheckoutBranch,
      handleStartCreateBranch,
      handleCreateAndCheckoutBranch,
      handleStartAiReviewOnFullDiff,
      handleCancelAiReviewRun,
      handleAskAiFollowUp,
    },
  });

  return {
    activeView: s.activeView,
    settingsViewModel,
    workspaceViewModel,
  };
}
